### PR TITLE
Djphan cards

### PR DESCRIPTION
**Pull request by djphan**

### CODE REVIEW

**Comment by djphan** [comment]
https://github.com/seanhealy/HacktoberfestYEG/issues/5 and https://github.com/seanhealy/HacktoberfestYEG/issues/6 addressed

**Comment by djphan** [comment]
Preview of the card changes screen shot 2018-10-16 at 11 34 21 am

**Comment by kdbanman** [comment]
Oh hi @djphan.  We github-meet again!

**Comment by seanhealy** [comment]
@djphan I REALLY like this idea but, want to do a bit of looking with one of our designers who I'm going to borrow to explore a couple other options around what we could do here if that's ok with you. 😄

**Comment by djphan** [comment]
Hehe sure that's ok :))).

**Comment by djphan** [comment]
I closed this PR since Hacktoberfest 2019 is kicked off and this design was for the old one :)

**Pull request closed without merging**
